GET http://localhost:4010/
###
POST http://localhost:4010/UserRegister
Content-Type: application/json

{
    "UserEmail": "siva@gmail.com", 
    "UserPassword": "Siva@123"
}



###
POST http://localhost:4010/Userlogin
Content-Type: application/json


{
      "UserEmail":"siva@gmail.com",
       "UserPassword":"Siva@123"
}

###
# uma
POST http://localhost:4010/AddInstitute
Content-Type: application/json

{
     
    "InstituteName": "College",
    "HeadName": "Management",
    "PrimaryEmail": "college@gmail.com",
    "PrimaryContactNumber": "9541257878",
    "SecondaryEmail": "college@gmail.com",
    "SecondaryContactNumber": "8547854785",
    "BatchYear": "2018",
    "SelectBatch": "Y-Batch",
    "Address": "Vijayawada",
    "City": "Vijayawada",
    "InstituteCode": "8547",
    "InstituteType": "College",
    "AxiosPlans": "LMS",
    "Password": "college@1234"
}
###
GET http://localhost:4010/allAddInstitutes

###
PUT http://localhost:4010/UpdateInstitute/654b2e12dc639a0f228d0af9
Content-Type: application/json
 
 {
    "InstituteName": "Ramya",
    "HeadName": "HR",
    "PrimaryEmail": "ramya@gmail.com",
    "PrimaryContactNumber": "9658745874",
    "SecondaryEmail": "ramya@gmail.com",
    "SecondaryContactNumber": "9658748547",
    "BatchYear": "2015",
    "SelectBatch": "U-Batch",
    "Address": "Vijayavada",
    "City": "Vijayavada",
    "InstituteCode": "1276",
    "InstituteType": "Training Institute",
    "AxiosPlans": "Mock Interview",
    "Password": "Ramya@1234"
 }
 
###
DELETE http://localhost:4010/deleteInstitute/652f7fe1e5bbc63a72e0c434

###
GET http://localhost:4010/individualInstitute/654231e2988003b306627265
###
GET http://localhost:4010/individualInstituteNames/Corporate-Office
###
POST http://localhost:4010/AddUsers
Content-Type: application/json

{ 
    "Regdid": "854DR7458",
    "FirstName": "Sai",
    "LastName": "Kumar",
    "userEmail": "saikol@gmail.com",
    "userNumber": "9632587412",
    "BatchYear": "2011",
    "SelectBatch": "S-Batch",
    "InstituteType": "Siva-krishna",
    "AxiosPlans": "9 Months",
    "Password": "Sai@gmail.com",
    
    "ExpiryDate": "21-11-2024"
}
###
POST http://localhost:4010/UserDetailslogin
Content-Type: application/json


{
      "userEmail":"Kalyan@gmail.com",
       "Password":"Charan@1234"
}
###
GET http://localhost:4010/allUsersData
###
GET http://localhost:4010/individualUser/65423234988003b30662726d

###
POST http://localhost:4010/ByBatchData
Content-Type: application/json

{ 
    
    "BatchYear": "2015",
    "SelectBatch": "U-Batch",
    "InstituteType": "Ramya",
    "AxiosPlans": "3 Months"
  
}
###
POST http://localhost:4010/ByListData
Content-Type: application/json

{ 
    
    "aboveData": "mail",
    "institutionpara": "a combining form meaning “guard against,” occurring in loanwords from French, or, via French, from Italian: parachute; parasol.",
    "InstituteType": "Ramya",
    "AxiosPlans": "9 Months"
  
}
###
PUT http://localhost:4010/ByBatchData/Corporate-Office
Content-Type: application/json

{

      "BatchYear": "9654",
    "SelectBatch": "P-Batch",
    "AxiosPlans": "888888 Months"

}

###
PUT http://localhost:4010/ByListData/Corporate-Office
Content-Type: application/json

{

      "aboveData": "Siva",
    "institutionpara": "siva koteswara rao",
    "AxiosPlans": "99 Months"
}
###
 
GET http://localhost:4010/InstituteData123/Corporate-Office


//Learn Path Data 
###
POST http://localhost:4010/AddVideoPath
Content-Type: application/json

{
     
    "VideofolderName": "Mechanical"
    
}
###
GET http://localhost:4010/allAddVideosData
###
PUT http://localhost:4010/UpdateVideosDetails/655c3eaa8080305e35b2acca
Content-Type: application/json
 
 {
    "VideofolderName": "Codding"
    
 }

###
GET http://localhost:4010/DisplayIndividualVideo/655c36a4442a34cc532789f8
###
DELETE http://localhost:4010/deleteVideo/655c3eaa8080305e35b2acca
###



POST http://localhost:4010/AddVideoFilesData
Content-Type: application/json
 
 {

      "VideofolderName": "React-Js",
    "VideoTitleName": "ReactJs Intro",
    "SourceName": "youtube",
    "Video1": "https://youtu.be/Y6aYx_KKM7A?si=_bNMhMJhjB-UTOcr"
}
###
GET http://localhost:4010/DisplayAllVideos
###
GET http://localhost:4010/foldersVideoData/React-Js
###
 GET http://localhost:4010/v2/subjects
###
GET http://localhost:4010/v4/getbasic
###
POST http://localhost:4010/addlearningpath
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiNjUyZDE1NGRlNWNkYmUzZTg5OTEyMGY0IiwiaWF0IjoxNzAyODkwNDI3LCJleHAiOjE3Mzg4OTA0Mjd9.F8zeKKmULpZfBtBZUDeAH6SCloJcz1Y7X4UIz34k79U

{

    "learningPathTitle":"uma",
  "relevantSkillTags":"ffffffff",
  "coverLetter":"ffs",
  "difficultyLevel":"trrrrrrrrrrr",
  "subscription":"ttttttttttt",
  "price":"trrrrrrrrrrrr",
  "discount":"trrrrrrrrrr",
  "AboutLearnPath":"rttttttttt",
  "authorName":"trtrrrrrrrrrrrr",
  "learningimg":"rtttttttttt",
  "fileName":"ttttttttt",
  "requirements":"ttttttttttttt"
  
}
###
GET http://localhost:4010/v4/getbasic
###
GET http://localhost:4010/v1/getMCQs/657ae56007e4c0be034337e7/657ae5a507e4c0be03433806
###
GET http://localhost:4010/U1/allassessment
###
GET http://localhost:4010/v4/getbasic/658a75aef473d32fde648726/658a75f7f473d32fde648739/658a7fdef473d32fde648a2d
###

PUT http://localhost:4010/v4/658a75aef473d32fde648726/chapters/658a75f7f473d32fde648739/codingbasic/658a9281f473d32fde648ca1
Content-Type: application/json
 
 {
      
    "Subjects" : "react",
    "Chapters" : "react hooks",
    "Title" : "MCV",
    "Programminglanguage" : "MCV",
    "Description" : "mcvdata",
    "Constraints" : "mcvdata"
        
 }
###
POST http://localhost:4010/U2/Blogs
Content-Type: application/json

{

    "Title" : "react",
    "Tags" : "react hooks",
    "Author" : "MCV",
    "Description" : "MCV",
    "Image" : "mcvdata"
   
}












 
 
 


 

